### ISSUE TITLE
improvements to note()

### ISSUE THREAD

**Issue by jmbarbone** [jmbarbone/jordan#12]
### Todo
- [x] Change class to simplify `note`
- [x] Add `note` class to objects?  This can call `print.note()` to show the note with the appropriate function and then print with another method?
- [ ] ~Allow option to suppress notes when calling objects (`jordan.show_note`?)~
